### ISSUE TITLE
9GAGAG is live!

### ISSUE THREAD

**Issue by tongrhj** [tongrhj/tictactoe-reborn#2]
@cbas @sevresbabylone 9GAGAG vAlpha is now ready for viewing! By Yong Jun, Jared and Jerry

Personally I would like to know how to create a neat CSS drop-down menu

**Comment by sebdeckers** [comment]
For dropdowns have a look at: http://codepen.io/tag/dropdown/
Related to that are the label/checkbox CSS hacks: https://css-tricks.com/the-checkbox-hack/

:+1: Amazing work team!

Feedback:
- Love the use of unicode emoji :fire: 
- Avoid inline styles `style="width: 600px;"` (twice)
- Almost any time you use `container` in a class name, it's a sign you should either rename the class to be more semantic, or change the HTML tree.
- Instead of `#sidebar-container` consider `<aside>` as a semantic element name.
- Avoid comments like `<!-- end div#sidebar-container -->` which are potentially incorrect after refactoring the HTML, or a chore to maintain at best.

**Comment by tongrhj** [comment]
@jerrygraced @yongjun21 **In case you haven't seen Seb's feedback**

The repository is now at https://github.com/tongrhj/wdi-sg-9GAG and live on https://tongrhj.github.io/wdi-sg-9GAG
